services:
  stay-link.server:
    image: ${DOCKER_REGISTRY-}staylinkserver

    extends: 
      file: docker-compose.yml
      service: stay-link.server
            

    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      # - ASPNETCORE_Kestrel__Certificates__Default__Password=password
      # - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx

    ports:
      - "8081:443"
      - "8080:80"

    volumes:
      - ~/.aspnet/https:/https:ro
