services:
  stay-link.server:
    image: ${DOCKER_REGISTRY-}staylinkserver
    environment:
      - ConnectionStrings__Default="Server=postgres;Port=5432;Database=booking-system-db;User Id=postgres;Password=root;"
    build:
      context: stay-link.Server
      dockerfile: Dockerfile
    ports:
      - "8081:443"
      - "8080:80"
    depends_on:
      postgresql:
        condition: service_healthy
    networks:
      - app-network

  postgresql:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: booking-system-db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./stay-link.Server/booking-db.sql:/docker-entrypoint-initdb.d/booking-db.sql

    healthcheck:
        test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
        interval: 10s
        retries: 5
        start_period: 30s
        timeout: 10s

    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
