services:
  stay-link.server:
    image: ${DOCKER_REGISTRY-}staylinkserver
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Host=${POSTGRES_SERVER};Port=${POSTGRES_PORT};Database=${POSTGRES_DB};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}
      - ASPNETCORE_URLS=${ASPNETCORE_URLS}
      - Jwt__Secret=${JWT_SECRET}
      - FRONTEND_URL=${FRONTEND_URL}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
    build:
      context: stay-link.Server
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      postgresql:
        condition: service_healthy
    networks:
      - app-network

  postgresql:
    image: postgres:16
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}

    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./stay-link.Server/booking-db.sql:/docker-entrypoint-initdb.d/booking-db.sql

    healthcheck:
        test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
        interval: 10s
        retries: 5
        start_period: 30s
        timeout: 10s

    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
